## pandas 3 ejercicios

In [1]:
import numpy as np
import pandas as pd

### En la siguiente celda se guarda la información del excel

In [3]:
df1 = pd.read_excel("../data/Airbnb_NYC.xlsx", sheet_name = "NYC1")
df2 = pd.read_excel("../data/Airbnb_NYC.xlsx", sheet_name = "NYC2")

### Ejercicio 0:
- Une los dos DataFrames anteriores por la columna **`id`**. Guarda en nuevo DataFrame en **`df`**

In [4]:
df = pd.merge(right = df1, left = df2, on = "id")

df.head()

id  price  minimum_nights  number_of_reviews last_review  \
0  2539.0  149.0             1.0                9.0  2018-10-19   
1  2595.0  225.0             1.0               45.0  2019-05-21   
2  3647.0  150.0             3.0                0.0         NaT   
3  3831.0   89.0             1.0              270.0  2019-07-05   
4  5022.0   80.0            10.0                9.0  2018-11-19   

   reviews_per_month  calculated_host_listings_count  availability_365  \
0               0.21                             6.0             365.0   
1               0.38                             2.0             355.0   
2                NaN                             1.0             365.0   
3               4.64                             1.0             194.0   
4               0.10                             1.0               0.0   

                                               name  host_id    host_name  \
0                Clean & quiet apt home by the park     2787         John   
1                             Skylit Midtown Castle     2845     Jennifer   
2               THE VILLAGE OF HARLEM....NEW YORK !     4632    Elisabeth   
3                   Cozy Entire Floor of Brownstone     4869  LisaRoxanne   
4  Entire Apt: Spacious Studio/Loft by central park     7192        Laura   

   municipio        barrio  latitude  longitude        room_type  
0   Brooklyn    Kensington  40.64749  -73.97237     Private room  
1  Manhattan       Midtown  40.75362  -73.98377  Entire home/apt  
2  Manhattan        Harlem  40.80902  -73.94190     Private room  
3   Brooklyn  Clinton Hill  40.68514  -73.95976  Entire home/apt  
4  Manhattan   East Harlem  40.79851  -73.94399  Entire home/apt

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype         
---  ------                          --------------  -----         
 0   id                              48895 non-null  float64       
 1   price                           48895 non-null  float64       
 2   minimum_nights                  48895 non-null  float64       
 3   number_of_reviews               48895 non-null  float64       
 4   last_review                     38843 non-null  datetime64[ns]
 5   reviews_per_month               38843 non-null  float64       
 6   calculated_host_listings_count  48895 non-null  float64       
 7   availability_365                48895 non-null  float64       
 8   name                            48870 non-null  object        
 9   host_id                         48895 non-null  int64         
 10  host_name                       48873 non-null  object        
 11  mu

In [6]:
df.shape

(48895, 16)

### Ejercicio 1:
- Si quiero hospedarme en Manhattan una sola noche y para elegir el Airbnb me guio por el que tenga el mayor número de reviews, ¿donde me debería de hospedar?

In [7]:
df[(df["municipio"] == "Manhattan") & (df["minimum_nights"] >= 1)].sort_values("number_of_reviews", ascending = False).head(3)

id  price  minimum_nights  number_of_reviews last_review  \
2031  903972.0   49.0             1.0              607.0  2019-06-21   
2030  903947.0   49.0             1.0              597.0  2019-06-23   
2015  891117.0   49.0             1.0              594.0  2019-06-15   

      reviews_per_month  calculated_host_listings_count  availability_365  \
2031               7.75                             3.0             293.0   
2030               7.72                             3.0             342.0   
2015               7.57                             3.0             339.0   

                                name  host_id host_name  municipio  barrio  \
2031      Great Bedroom in Manhattan  4734398        Jj  Manhattan  Harlem   
2030  Beautiful Bedroom in Manhattan  4734398        Jj  Manhattan  Harlem   
2015    Private Bedroom in Manhattan  4734398        Jj  Manhattan  Harlem   

      latitude  longitude     room_type  
2031  40.82085  -73.94025  Private room  
2030  40.82124  -73.93838  Private room  
2015  40.82264  -73.94041  Private room

### Ejercicio 2:
- Busco un Airbnb en el municipio donde el precio promedio de alquiler sea el más bajo y la cantidad de review por mes sea el mayor. ¿Cuáles son las 3 habitaciones que mejor se adaptan a estos criterios?

In [10]:
municipio = df.groupby("municipio")[["price", "reviews_per_month"]].mean().sort_values("price").index[0] #Bronx

In [11]:
municipio

'Bronx'

In [12]:
df[df["municipio"] == municipio].sort_values("reviews_per_month", ascending = False).head(3)

id  price  minimum_nights  number_of_reviews last_review  \
23371  18914730.0   95.0             1.0              266.0  2019-06-28   
41945  32595490.0   95.0             2.0               27.0  2019-07-05   
42252  32801214.0  150.0             1.0               24.0  2019-06-20   

       reviews_per_month  calculated_host_listings_count  availability_365  \
23371              10.34                             1.0             345.0   
41945               8.62                             1.0             153.0   
42252               8.37                             5.0             247.0   

                                                  name    host_id  \
23371                     IDEALLY LOCATED COZY COTTAGE    1776707   
41945  Peaceful 2 Bedroom apartment in a private house  245003299   
42252       TW #6 Private Suite 2nd Fl.  1 to 4 Guests  211136294   

            host_name municipio         barrio  latitude  longitude  \
23371            Luis     Bronx    Throgs Neck  40.83051  -73.82511   
41945         Yoselyn     Bronx   Clason Point  40.80924  -73.85107   
42252  Sharon & Erika     Bronx  Schuylerville  40.83560  -73.83369   

             room_type  
23371  Entire home/apt  
41945  Entire home/apt  
42252     Private room

### Ejercicio 3:
- Quiero rentar un Airbnb completo por un total de 200 días, en Brooklyn o Manhattan; no quiero pagar más de 150 dólares por noche, ¿Cuáles son las 5 opciones más economicas que me ofrece Airbnb?

In [ ]:
df[(df["municipio"].isin(["Brooklyn", "Manhattan"])) & (df["price"] <= 150) & (df["availability_365"] >= 200)].sort_values("price").head()

### Ejercicio 4:
- En un nuevo Dataframe muestra por municipio: el número de habitaciones tipo individual, casa o departamento entero y compartido; también muestra en otra columna el precio promedio de todas las habitaciones por municipio.

In [ ]:
df.groupby(["municipio", "room_type"]).agg({"id"    : ["count"],
                                            "price" : ["mean"]})

### Ejercicio 5:
- Crea una nueva columna en el DataFrame original, con el rating de acuerdo a la siguiente formula, donde las variables son: puntaje del municipio, número de reviews y disponibilidad de la habitación al año.

- Formula: Rating = (Puntaje de ciudad) + (número de review/ 629) + (disponibilidad / 365).

- El puntaje para cada ciudad es el siguiente {"Manhattan" : 10/10, "Brooklyn" : 8/10, "Queens" : 6/10, "Staten Island" : 4/10, "Bronx" : 2/10}.

In [ ]:
def rating(ciudad, review, disp):
    
    if ciudad == "Manhattan":
        return 10/10 + review/629 + disp/365
    
    elif ciudad == "Brooklyn":
        return 8/10 + review/629 + disp/365
    
    elif ciudad == "Queens":
        return 6/10 + review/629 + disp/365
    
    elif ciudad == "State Island":
        return 4/10 + review/629 + disp/365
    
    else:
        return 2/10 + review/629 + disp/365

In [ ]:
df["rating"] = df.apply(lambda x: rating(x["municipio"], x["number_of_reviews"], x["availability_365"]), axis = 1)

### Ejercicio 6:
- Encuentra las 5 habitaciones de cada municipio con mayor rating.

In [ ]:
df.sort_values(["municipio", "rating"], ascending = False).groupby("municipio").head(5)

### Ejercicio 7:
- Crea un DataFrame con la cantidad de reviews de cada municipio de acuerdo a tipo de habitación.

In [ ]:
df.groupby(by = ["municipio", "room_type"]).agg({"number_of_reviews" : [np.mean]})

### Ejercicio 8:
- Encuentra los 10 barrios con mayor precio por habitación individual.

In [ ]:
df[df["room_type"] == "Private room"][["barrio", "price"]].sort_values("price", ascending = False).head(10)

### Ejercicio 9:
- Encuentra el barrio con mejor rating de cada municipio.

In [ ]:
#df[df["room_type"] == "Entire home/apt"][["barrio", "price", "municipio", "rating"]].sort_values("price").groupby("municipio").aggregate({"rating" : "max"})


df[df["room_type"] == "Entire home/apt"][["barrio", "price", "municipio", "rating"]].sort_values("rating", ascending = False).groupby("municipio").head(1)



### Ejercicio 10:
- Del resultado anterio, selecciona los 2 barrios con el menor precio por "dep/casa completo".

In [ ]:
df[df["room_type"] == "Entire home/apt"][["barrio", "price", "municipio", "rating"]].sort_values("price", ascending = True).groupby("municipio").head(2)